export const attractionsDB = {
  Paris: {
    hotels: [
      { name: 'Le Marais Boutique Hotel', address: '42 Rue de Rivoli, 75004', area: 'Le Marais', rating: '4.5' },
      { name: 'Hotel Lutetia', address: '45 Boulevard Raspail, 75006', area: '6th Arrondissement', rating: '4.8' },
      { name: 'Pullman Paris La Defense', address: '75 Boulevard de la Mission Marchal Juin, 92400 Courbevoie', area: 'La Défense', rating: '4.3' },
    ],
    attractions: [
      {
        name: 'Eiffel Tower',
        address: '5 Avenue Anatole France, 75007',
        area: '7th Arrondissement',
        description: 'Iconic iron lattice monument and symbol of Paris',
        category: 'sightseeing',
        cost: '$15-25 per person',
        duration: '2-3 hours',
      },
      {
        name: 'Louvre Museum',
        address: 'Rue de Rivoli, 75001',
        area: '1st Arrondissement',
        description: 'Worlds largest art museum featuring Mona Lisa and Venus de Milo',
        category: 'sightseeing',
        cost: '$17 per person',
        duration: '3-4 hours',
      },
      {
        name: 'Arc de Triomphe',
        address: 'Place Charles de Gaulle, 75008',
        area: '8th Arrondissement',
        description: 'Monument honoring those who died in French wars, with panoramic city views',
        category: 'sightseeing',
        cost: '$12 per person',
        duration: '1-2 hours',
      },
      {
        name: 'Notre-Dame Cathedral',
        address: '6 Parvis Notre-Dame, 75004',
        area: '4th Arrondissement',
        description: 'Medieval Catholic cathedral with stunning Gothic architecture',
        category: 'sightseeing',
        cost: 'Free (exterior), $10 for interior',
        duration: '1.5 hours',
      },
      {
        name: 'Sacré-Cœur Basilica',
        address: '35 Rue du Chevalier de la Barre, 75018',
        area: 'Montmartre',
        description: 'White-domed basilica overlooking Paris with beautiful interior mosaics',
        category: 'sightseeing',
        cost: 'Free (exterior), $6 for dome',
        duration: '2 hours',
      },
      {
        name: 'L\'Arpège Restaurant',
        address: '84 Rue de Varenne, 75007',
        area: '7th Arrondissement',
        description: 'Michelin 3-star restaurant with seasonal French cuisine',
        category: 'dining',
        cost: '$150-200 per person',
        duration: '2.5 hours',
      },
      {
        name: 'Café de Flore',
        address: '172 Boulevard Saint-Germain, 75006',
        area: '6th Arrondissement',
        description: 'Historic café frequented by famous artists and writers',
        category: 'dining',
        cost: '$20-40 per person',
        duration: '1-2 hours',
      },
    ],
    nearbyResorts: [],
  },
  Tokyo: {
    hotels: [
      { name: 'The Peninsula Tokyo', address: '1-8-1 Yurakucho, Chiyoda-ku', area: 'Ginza', rating: '4.8' },
      { name: 'Shinjuku Prince Hotel', address: '1-30-1 Kabukicho, Shinjuku-ku', area: 'Shinjuku', rating: '4.4' },
      { name: 'Mitsui Garden Hotel Premier Ginza', address: '2-11-6 Ginza, Chuo-ku', area: 'Ginza', rating: '4.6' },
    ],
    attractions: [
      {
        name: 'Senso-ji Temple',
        address: '2-3-1 Asakusa, Taito-ku',
        area: 'Asakusa',
        description: 'Ancient Buddhist temple with iconic red lantern and street market',
        category: 'sightseeing',
        cost: 'Free',
        duration: '1.5-2 hours',
      },
      {
        name: 'Meiji Shrine',
        address: '1-1 Yoyogikamizonocho, Shibuya-ku',
        area: 'Shinjuku',
        description: 'Peaceful Shinto shrine dedicated to Emperor Meiji, surrounded by forest',
        category: 'sightseeing',
        cost: 'Free',
        duration: '1.5 hours',
      },
      {
        name: 'Shibuya Crossing',
        address: 'Dogenzaka, Shibuya-ku',
        area: 'Shibuya',
        description: 'Worlds busiest pedestrian crossing, surrounded by restaurants and shops',
        category: 'sightseeing',
        cost: 'Free',
        duration: '30-45 minutes',
      },
      {
        name: 'Tokyo Skytree',
        address: '1-1-2 Oshiage, Sumida-ku',
        area: 'Sumida',
        description: 'Tallest structure in Japan with observation decks for city views',
        category: 'sightseeing',
        cost: '$18-25 per person',
        duration: '2-3 hours',
      },
      {
        name: 'Choji',
        address: '2-28-5 Asakusa, Taito-ku',
        area: 'Asakusa',
        description: 'Famous traditional restaurant serving tempura since 1881',
        category: 'dining',
        cost: '$25-50 per person',
        duration: '1-1.5 hours',
      },
      {
        name: 'Tsukiji Outer Market',
        address: '2-16-7 Tsukiji, Chuo-ku',
        area: 'Tsukiji',
        description: 'Vibrant seafood market with fresh sushi and grilled options',
        category: 'dining',
        cost: '$15-30 per person',
        duration: '1-2 hours',
      },
    ],
    nearbyResorts: [],
  },
  'New York': {
    hotels: [
      { name: 'The Plaza Hotel', address: '768 Fifth Avenue, Manhattan', area: 'Midtown', rating: '4.6' },
      { name: 'Four Seasons Hotel New York', address: '57 East 57th Street, Manhattan', area: 'Midtown', rating: '4.8' },
      { name: 'The Standard High Line', address: '848 Washington Street, Manhattan', area: 'Chelsea', rating: '4.5' },
    ],
    attractions: [
      {
        name: 'Statue of Liberty',
        address: 'Liberty Island, Manhattan',
        area: 'Statue Island',
        description: 'Iconic colossal neoclassical sculpture, UNESCO World Heritage Site',
        category: 'sightseeing',
        cost: '$19 per person (ferry)',
        duration: '2-3 hours',
      },
      {
        name: 'Central Park',
        address: '59th Street to 110th Street, Manhattan',
        area: 'Midtown',
        description: 'Large urban park with lakes, meadows, and iconic monuments',
        category: 'leisure',
        cost: 'Free',
        duration: '2-4 hours',
      },
      {
        name: 'Empire State Building',
        address: '20 West 34th Street, Manhattan',
        area: 'Midtown',
        description: 'Iconic Art Deco skyscraper with observation decks',
        category: 'sightseeing',
        cost: '$25-43 per person',
        duration: '1.5-2 hours',
      },
      {
        name: 'Times Square',
        address: 'Intersection of Broadway & 42nd Street, Manhattan',
        area: 'Midtown',
        description: 'Bright commercial intersection with Broadway theaters and restaurants',
        category: 'sightseeing',
        cost: 'Free to walk',
        duration: '30-60 minutes',
      },
      {
        name: 'Eleven Madison Park',
        address: '11 Madison Avenue, Manhattan',
        area: 'Midtown',
        description: 'Michelin 3-star restaurant with innovative American cuisine',
        category: 'dining',
        cost: '$160-200 per person',
        duration: '2.5-3 hours',
      },
      {
        name: 'Joe\'s Pizza',
        address: '7 Carmine Street, Manhattan',
        area: 'Greenwich Village',
        description: 'Iconic NYC pizza joint with thin-crust slices',
        category: 'dining',
        cost: '$3-5 per person',
        duration: '30 minutes',
      },
    ],
    nearbyResorts: [],
  },
  Maldives: {
    hotels: [
      { name: 'Conrad Rangali Island', address: 'Rangali Island, Dhaalu Atoll', area: 'Dhaalu Atoll', rating: '4.9' },
      { name: 'Soneva Jani', address: 'Medhufaru Island, Noonu Atoll', area: 'Noonu Atoll', rating: '4.8' },
      { name: 'Lux South Ari Atoll', address: 'South Ari Atoll', area: 'South Ari Atoll', rating: '4.7' },
    ],
    attractions: [
      {
        name: 'Snorkeling in Coral Gardens',
        address: 'Various atoll reefs, Maldives',
        area: 'All Atolls',
        description: 'Crystal-clear waters with vibrant coral reefs and tropical fish',
        category: 'adventure',
        cost: '$30-50 per person',
        duration: '2-3 hours',
      },
      {
        name: 'Dolphin Watching',
        address: 'North Ari Atoll, Maldives',
        area: 'North Ari Atoll',
        description: 'Spot playful dolphins at sunrise or sunset',
        category: 'adventure',
        cost: '$40-60 per person',
        duration: '2-3 hours',
      },
      {
        name: 'Spa & Wellness',
        address: 'Island Resorts, Maldives',
        area: 'Various',
        description: 'Indulge in world-class spa treatments and wellness activities',
        category: 'leisure',
        cost: '$100-200 per person',
        duration: '1-2 hours',
      },
      {
        name: 'Island Hopping',
        address: 'Various islands, Maldives',
        area: 'Various Atolls',
        description: 'Visit local islands to experience Maldivian culture',
        category: 'sightseeing',
        cost: '$30-50 per person',
        duration: '3-4 hours',
      },
      {
        name: 'Fresh Seafood Dinner',
        address: 'Resort restaurants, Maldives',
        area: 'Various',
        description: 'Beachfront dining with fresh catch and tropical flavors',
        category: 'dining',
        cost: '$50-100 per person',
        duration: '2-2.5 hours',
      },
      {
        name: 'Scuba Diving',
        address: 'Various dive sites, Maldives',
        area: 'Various Atolls',
        description: 'Explore underwater world with professional diving instructors',
        category: 'adventure',
        cost: '$80-120 per person',
        duration: '3-4 hours',
      },
    ],
    nearbyResorts: [],
  },
  Barcelona: {
    hotels: [
      { name: 'Mandarin Oriental Barcelona', address: 'Passeig de Gracia, 38-40', area: 'Eixample', rating: '4.8' },
      { name: 'Hotel Arts Barcelona', address: 'Marina, 19-21', area: 'Barceloneta', rating: '4.7' },
      { name: 'Almanac Barcelona Hotel', address: 'Passeig de Gracia, 84', area: 'Eixample', rating: '4.6' },
    ],
    attractions: [
      {
        name: 'Sagrada Família',
        address: 'Carrer de Mallorca, 401',
        area: 'Eixample',
        description: 'Iconic basilica with unique architecture, under construction since 1883',
        category: 'sightseeing',
        cost: '$23 per person',
        duration: '1.5-2 hours',
      },
      {
        name: 'Park Güell',
        address: 'Carrer d\'Olot, 5',
        area: 'Gràcia',
        description: 'Colorful mosaic park with panoramic city views',
        category: 'sightseeing',
        cost: '$13-15 per person',
        duration: '2-3 hours',
      },
      {
        name: 'Gothic Quarter',
        address: 'Barrio Gótico, Barcelona',
        area: 'Gothic Quarter',
        description: 'Medieval neighborhood with narrow streets and historic buildings',
        category: 'sightseeing',
        cost: 'Free to walk',
        duration: '2-3 hours',
      },
      {
        name: 'Las Ramblas',
        address: 'Passeig de les Rambles',
        area: 'Las Ramblas',
        description: 'Famous tree-lined pedestrian street with street performers',
        category: 'sightseeing',
        cost: 'Free',
        duration: '1-2 hours',
      },
      {
        name: 'Cal Pep',
        address: 'Plaça de les Olles, 8',
        area: 'Gothic Quarter',
        description: 'Famous seafood restaurant with fresh daily catches',
        category: 'dining',
        cost: '$30-50 per person',
        duration: '1.5-2 hours',
      },
      {
        name: 'Cervecería Catalana',
        address: 'Passeig de Gràcia, 103',
        area: 'Eixample',
        description: 'Popular tapas bar with Spanish specialties and local atmosphere',
        category: 'dining',
        cost: '$20-40 per person',
        duration: '1-2 hours',
      },
    ],
    nearbyResorts: [],
  },
};

export default attractionsDB;
